// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function calcFreq(accm, line) {
  if (line.indexOf("+") > -1) {
    return accm + Caml_format.caml_int_of_string(line.substr(1)) | 0;
  } else {
    return accm + Caml_format.caml_int_of_string(line) | 0;
  }
}

var lines = Fs.readFileSync("./src/day1/input1.txt", "utf8").split("\n");

var res = Belt_Array.reduce(lines, 0, calcFreq);

console.log(res);

exports.calcFreq = calcFreq;
exports.lines = lines;
exports.res = res;
/* lines Not a pure module */
