// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Belt_HashSetInt = require("bs-platform/lib/js/belt_HashSetInt.js");

var lines = Fs.readFileSync("./src/day1/input1.txt", "utf8").split("\n");

var resultsTable = Belt_HashSetInt.make(lines.length);

function findDuplicate(allLines, _num, _accm) {
  while(true) {
    var accm = _accm;
    var num = _num;
    var match = Belt_Array.get(allLines, num);
    var line = match !== undefined ? match : "";
    var res = line.indexOf("+") > -1 ? accm + Caml_format.caml_int_of_string(line.substr(1)) | 0 : accm + Caml_format.caml_int_of_string(line) | 0;
    if (Belt_HashSetInt.has(resultsTable, res)) {
      console.log("Found res", res);
      return true;
    } else {
      Belt_HashSetInt.add(resultsTable, res);
      var nextNum = (num + 1 | 0) === allLines.length ? 0 : num + 1 | 0;
      _accm = res;
      _num = nextNum;
      continue ;
    }
  };
}

findDuplicate(lines, 0, 0);

exports.lines = lines;
exports.resultsTable = resultsTable;
exports.findDuplicate = findDuplicate;
/* lines Not a pure module */
